In [16]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

from sklearn.ensemble import RandomForestClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.linear_model import Perceptron
from sklearn.linear_model import LogisticRegression
from sklearn import svm
from sklearn.neighbors import KNeighborsClassifier

from sklearn.metrics import confusion_matrix
from sklearn.naive_bayes import GaussianNB
from sklearn import metrics

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder, StandardScaler
#from keras.models import Sequential
#from keras.layers import Dense
#from numpy import loadtxt

# Reading .csv file

In [17]:
dataset = pd.read_csv('grid.csv')
print (dataset)

           tau1      tau2      tau3      tau4        p1        p2        p3  \
0      2.959060  3.079885  8.381025  9.780754  3.763085 -0.782604 -1.257395   
1      9.304097  4.902524  3.047541  1.369357  5.067812 -1.940058 -1.872742   
2      8.971707  8.848428  3.046479  1.214518  3.405158 -1.207456 -1.277210   
3      0.716415  7.669600  4.486641  2.340563  3.963791 -1.027473 -1.938944   
4      3.134112  7.608772  4.943759  9.857573  3.525811 -1.125531 -1.845975   
...         ...       ...       ...       ...       ...       ...       ...   
59995  2.930406  2.376523  9.487627  6.187797  3.343416 -1.449106 -0.658054   
59996  3.392299  2.954947  1.274827  6.894759  4.349512 -0.952437 -1.663661   
59997  2.364034  8.776391  2.842030  1.008906  4.299976 -0.943884 -1.380719   
59998  9.631511  2.757071  3.994398  7.821347  2.514755 -0.649915 -0.966330   
59999  6.530527  4.349695  6.781790  8.673138  3.492807 -1.532193 -1.390285   

             p4        g1        g2        g3      

# Pre-processing (Replacing String Values with Numerical)

In [18]:
#dataset['Glucose'].replace(0, 121.1825, inplace = True)
#dataset['BloodPressure'].replace(0, 69.1455, inplace = True)
#dataset['SkinThickness'].replace(0, 20.935, inplace = True)
#dataset['Insulin'].replace(0, 80.254, inplace = True)
#dataset['BMI'].replace(np.NaN, 32.193, inplace = True)
#dataset['DiabetesPedigreeFunction'].replace(0, 0.47093, inplace = True)
#dataset['Age'].replace(0, 33, inplace = True)
dataset['stabf'].replace('unstable', 0, inplace = True)
dataset['stabf'].replace('stable', 1, inplace = True)
print(dataset)

           tau1      tau2      tau3      tau4        p1        p2        p3  \
0      2.959060  3.079885  8.381025  9.780754  3.763085 -0.782604 -1.257395   
1      9.304097  4.902524  3.047541  1.369357  5.067812 -1.940058 -1.872742   
2      8.971707  8.848428  3.046479  1.214518  3.405158 -1.207456 -1.277210   
3      0.716415  7.669600  4.486641  2.340563  3.963791 -1.027473 -1.938944   
4      3.134112  7.608772  4.943759  9.857573  3.525811 -1.125531 -1.845975   
...         ...       ...       ...       ...       ...       ...       ...   
59995  2.930406  2.376523  9.487627  6.187797  3.343416 -1.449106 -0.658054   
59996  3.392299  2.954947  1.274827  6.894759  4.349512 -0.952437 -1.663661   
59997  2.364034  8.776391  2.842030  1.008906  4.299976 -0.943884 -1.380719   
59998  9.631511  2.757071  3.994398  7.821347  2.514755 -0.649915 -0.966330   
59999  6.530527  4.349695  6.781790  8.673138  3.492807 -1.532193 -1.390285   

             p4        g1        g2        g3      

# KNN Classifier

In [19]:
X = dataset.drop('stabf', axis=1)
y = dataset['stabf']

X_train, X_test, y_train, y_test = train_test_split(X, y, shuffle =True, test_size=0.25, random_state=42)

sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

knn = KNeighborsClassifier(n_neighbors = 7)
knn.fit(X_train, y_train)
y_pred = knn.predict(X_test)

cm = confusion_matrix(y_test, y_pred)  
print ("Confusion Matrix : \n", cm)
print("")

print("Accuracy:", metrics.accuracy_score(y_test, y_pred))
print("Precision:", metrics.precision_score(y_test, y_pred))
print("Recall:", metrics.recall_score(y_test, y_pred))
print("F1-score:", (2*metrics.precision_score(y_test, y_pred)*metrics.recall_score(y_test, y_pred)) / (metrics.precision_score(y_test, y_pred) + metrics.recall_score(y_test, y_pred)))

Confusion Matrix : 
 [[9331  239]
 [ 402 5028]]

Accuracy: 0.9572666666666667
Precision: 0.9546231251186634
Recall: 0.9259668508287293
F1-score: 0.9400766570066373


# SVM Classifier

In [20]:
X = dataset.drop('stabf', axis=1)
y = dataset['stabf']

X_train, X_test, y_train, y_test = train_test_split(X, y, shuffle =True, test_size=0.25, random_state=42)

sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

clf = svm.SVC(kernel='linear')
clf.fit(X_train, y_train)
y_pred = clf.predict(X_test)

cm = confusion_matrix(y_test, y_pred)  
print ("Confusion Matrix : \n", cm)
print("")

print("Accuracy:", metrics.accuracy_score(y_test, y_pred))
print("Precision:", metrics.precision_score(y_test, y_pred))
print("Recall:", metrics.recall_score(y_test, y_pred))
print("F1-score:", (2*metrics.precision_score(y_test, y_pred)*metrics.recall_score(y_test, y_pred)) / (metrics.precision_score(y_test, y_pred) + metrics.recall_score(y_test, y_pred)))

Confusion Matrix : 
 [[9568    2]
 [   6 5424]]

Accuracy: 0.9994666666666666
Precision: 0.9996314043494287
Recall: 0.9988950276243094
F1-score: 0.9992630803242446


# Naive-Bayes Classifier

In [21]:
X = dataset.drop('stabf', axis=1)
y = dataset['stabf']

X_train, X_test, y_train, y_test = train_test_split(X, y, shuffle =True, test_size=0.25, random_state=42)

sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

gnb = GaussianNB()
gnb.fit(X_train, y_train)
y_pred = gnb.predict(X_test)

cm = confusion_matrix(y_test, y_pred)  
print ("Confusion Matrix : \n", cm)
print("")

print("Accuracy:", metrics.accuracy_score(y_test, y_pred))
print("Precision:", metrics.precision_score(y_test, y_pred))
print("Recall:", metrics.recall_score(y_test, y_pred))
print("F1-score:", (2*metrics.precision_score(y_test, y_pred)*metrics.recall_score(y_test, y_pred)) / (metrics.precision_score(y_test, y_pred) + metrics.recall_score(y_test, y_pred)))

Confusion Matrix : 
 [[9381  189]
 [ 106 5324]]

Accuracy: 0.9803333333333333
Precision: 0.9657173952475966
Recall: 0.9804788213627993
F1-score: 0.973042127387371


# Logistic Regression Classifier

In [22]:
X = dataset.drop('stabf', axis=1)
y = dataset['stabf']

X_train, X_test, y_train, y_test = train_test_split(X, y, shuffle =True, test_size=0.25, random_state=42)

sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

clf = LogisticRegression(random_state = 0)
clf.fit(X_train, y_train)
y_pred = clf.predict(X_test)

cm = confusion_matrix(y_test, y_pred)  
print ("Confusion Matrix : \n", cm)
print("")

print("Accuracy:", metrics.accuracy_score(y_test, y_pred))
print("Precision:", metrics.precision_score(y_test, y_pred))
print("Recall:", metrics.recall_score(y_test, y_pred))
print("F1-score:", (2*metrics.precision_score(y_test, y_pred)*metrics.recall_score(y_test, y_pred)) / (metrics.precision_score(y_test, y_pred) + metrics.recall_score(y_test, y_pred)))

Confusion Matrix : 
 [[9567    3]
 [   5 5425]]

Accuracy: 0.9994666666666666
Precision: 0.9994473102431835
Recall: 0.9990791896869244
F1-score: 0.9992632160618897


# Single Perceptron Classifier

In [23]:
X = dataset.drop('stabf', axis=1)
y = dataset['stabf']

X_train, X_test, y_train, y_test = train_test_split(X, y, shuffle =True, test_size=0.25, random_state=42)

sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

clf = Perceptron(tol=1e-3, random_state=0)
clf.fit(X_train, y_train)
y_pred = clf.predict(X_test)

cm = confusion_matrix(y_test, y_pred)  
print ("Confusion Matrix : \n", cm)
print("")

print("Accuracy:", metrics.accuracy_score(y_test, y_pred))
print("Precision:", metrics.precision_score(y_test, y_pred))
print("Recall:", metrics.recall_score(y_test, y_pred))
print("F1-score:", (2*metrics.precision_score(y_test, y_pred)*metrics.recall_score(y_test, y_pred)) / (metrics.precision_score(y_test, y_pred) + metrics.recall_score(y_test, y_pred)))

Confusion Matrix : 
 [[9541   29]
 [  25 5405]]

Accuracy: 0.9964
Precision: 0.9946632315053368
Recall: 0.9953959484346224
F1-score: 0.9950294550810014


# Decision Tree Classifier

In [24]:
X = dataset.drop('stabf', axis=1)
y = dataset['stabf']

X_train, X_test, y_train, y_test = train_test_split(X, y, shuffle =True, test_size=0.25, random_state=42)

sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

clf = DecisionTreeClassifier()
clf = clf.fit(X_train,y_train)
y_pred = clf.predict(X_test)

cm = confusion_matrix(y_test, y_pred)  
print ("Confusion Matrix : \n", cm)
print("")

print("Accuracy:", metrics.accuracy_score(y_test, y_pred))
print("Precision:", metrics.precision_score(y_test, y_pred))
print("Recall:", metrics.recall_score(y_test, y_pred))
print("F1-score:", (2*metrics.precision_score(y_test, y_pred)*metrics.recall_score(y_test, y_pred)) / (metrics.precision_score(y_test, y_pred) + metrics.recall_score(y_test, y_pred)))

Confusion Matrix : 
 [[9570    0]
 [   0 5430]]

Accuracy: 1.0
Precision: 1.0
Recall: 1.0
F1-score: 1.0


# Random Forest Classifier

In [25]:
X = dataset.drop('stabf', axis=1)
y = dataset['stabf']

X_train, X_test, y_train, y_test = train_test_split(X, y, shuffle =True, test_size=0.25, random_state=42)

sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

clf = RandomForestClassifier()
clf = clf.fit(X_train,y_train)
y_pred = clf.predict(X_test)

cm = confusion_matrix(y_test, y_pred)  
print ("Confusion Matrix : \n", cm)
print("")

print("Accuracy:", metrics.accuracy_score(y_test, y_pred))
print("Precision:", metrics.precision_score(y_test, y_pred))
print("Recall:", metrics.recall_score(y_test, y_pred))
print("F1-score:", (2*metrics.precision_score(y_test, y_pred)*metrics.recall_score(y_test, y_pred)) / (metrics.precision_score(y_test, y_pred) + metrics.recall_score(y_test, y_pred)))

Confusion Matrix : 
 [[9570    0]
 [   0 5430]]

Accuracy: 1.0
Precision: 1.0
Recall: 1.0
F1-score: 1.0


In [26]:
# Deep Learning Model

#X = dataset.drop('Outcome', axis=1)
#y = dataset['Outcome']

#X_train, X_test, y_train, y_test = train_test_split(X, y, shuffle =True, test_size=0.25, random_state=42)

#sc = StandardScaler()
#X_train = sc.fit_transform(X_train)
#X_test = sc.transform(X_test)

#model = Sequential()
#model.add(Dense(12, input_dim=8, activation='relu'))
#model.add(Dense(8, activation='relu'))
#model.add(Dense(1, activation='sigmoid'))

#model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])
#model.fit(X, y, epochs=150, batch_size=10)

#cm = confusion_matrix(y_test, y_pred)  
#print ("Confusion Matrix : \n", cm)
#print("")

#print("Accuracy:", metrics.accuracy_score(y_test, y_pred))
#print("Precision:", metrics.precision_score(y_test, y_pred))
#print("Recall:", metrics.recall_score(y_test, y_pred))
#print("F1-score:", (2*metrics.precision_score(y_test, y_pred)*metrics.recall_score(y_test, y_pred)) / (metrics.precision_score(y_test, y_pred) + metrics.recall_score(y_test, y_pred)))